### PR TITLE
Add ability to specify mime type

### PR DESCRIPTION
**Pull request by DanLeininger**
Allows the ability to choose another mime type for the output (like 'image/png' to keep transparency).

### CODE REVIEW

**Comment by jperasmus** [comment]
Hi, when will this be published to NPM?

**Comment by ericnograles** [comment]
@jperasmus Shoot, I had meant to push a new version when I merged this.  I'll cut a new minor version and get it out there today.

**Comment by jperasmus** [comment]
Awesome, thanks so much 🙏

**Comment by ericnograles** [comment]
@jperasmus `1.2.0` is out on NPM with this PR merged in, FYI

**Comment by jperasmus** [comment]
Nice, thanks for publishing it so fast

**Pull request merged**
